### PR TITLE
Registration name

### LINKED ISSUE #95: New manga on registration shows the name of an existing one instead of its own
When registering a new manga, with at least already one registered manga, and before reloading the page, the new SideBar manga entry shows the same name as one (if not the first?) of the existing manga entries.

Upon reloading the page, the name gets properly set again, and the bug is no longer visible.

**Expected behavior**
The newly added manga should display the right name in the sidebar, without needing a reload.

**To Reproduce**
1. Register one manga
2. Register a second manga (no matter which "+" button it's done through)
3. Display the sidebar
4. See two entries with the same name (Reload the page and the name will be correct and no longer buggy)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #95.

### CODE REVIEW

File: web-extension/engine/bookmycomics.js [hunk 1]
```diff
@@ -248,9 +251,9 @@ BmcEngine.prototype.register = function(label, cb) {
     return this._db.registerComic(label, this._comic.reader, this._comic.info, err => {
         LOGS.debug('S11', {'err': err});
         if (!err) {
-            this._forceMemoizeComic();
+            this._forceMemoizeComic(() => cb(err));
+            return ;
         }
-        return cb(err);
```
Comment (Joacchim) [inline web-extension/engine/bookmycomics.js:253]: beware, you're no longer calling the callback if `this._db.registerComic()` encountered an error.

File: web-extension/engine/bookmycomics.js [hunk 2]
```diff
@@ -268,9 +271,9 @@ BmcEngine.prototype.alias = function(comicId, cb) {
                      'manga': this._comic.name});
     return this._db.aliasComic(comicId, this._comic.reader, this._comic.info, err => {
         if (!err) {
-            this._forceMemoizeComic();
+            this._forceMemoizeComic(() => cb(err));
+            return ;
         }
-        return cb(err);
```
Comment (Joacchim) [inline web-extension/engine/bookmycomics.js:273]: likewise

File: web-extension/engine/bookmycomics.js [hunk 3]
```diff
@@ -293,9 +296,9 @@ BmcEngine.prototype.delete = function(comicId, reader, name, cb) {
     // removed the Comic/Source matching the current page)
     const completeDelete = err => {
         if (!err) {
-            this._forceMemoizeComic();
+            this._forceMemoizeComic(() => cb(err));
         }
-        return cb(err);
```
Comment (Joacchim) [inline web-extension/engine/bookmycomics.js:298]: and once more

**Review by Joacchim — CHANGES_REQUESTED** [review]
So far, it looks like despite the patch, the issue still persists

**Comment by Joacchim** [comment]
Maybe we should split this new test into a new file, or rename the existing one ?

The idea is that the current file should be used for basic Reader support testing, while your test is more geared towards generic web-extension mechanisms testing. Then, we could keep the basic reader testing parametrized on the reader, while your new test would be only parametrized on the browser, and use one fixed reader.

**Review by Joacchim — APPROVED** [review]
LGTM, will bypass CI which is encountering issues due to isekaiscans (currently in maintainance)
